### ISSUE TITLE
Which features are a available and which are not?

### ISSUE THREAD

**Issue by frankgerhardt** [pdsinterop/php-solid-server#46] opened 2021-01-18 09:11 UTC
Maybe I'm blind or my browser renders it badly. From the main page:

![image](https://user-images.githubusercontent.com/550621/104894628-3cbd0b80-5975-11eb-9c71-85a5f9bb1b83.png)

In such a list I'd expect some checked check boxes and some uncheck check boxes. Which raises the quesiton what available?

Like (in Markdown):
- [ ] unchecked
- [x] checked

**Comment by Potherca** [comment] 2021-01-18 15:19
Hi @frankgerhardt, Thank you for pointing this out!

There's nothing wrong with your browser. We're just _way_ behind with updating our documentation. :disappointed:

Current @poef, @ylebre, and I are hard at work trying to complete the implementation of [milestones 4. (Social web apps)](https://github.com/pdsinterop/project-admin/blob/master/milestones.md).

Most of the other features are fully functional, we just never got around to actually checking those boxes. (Although the code still needs cleaning up and there might be some bugs caused by hard-coded values).

You can get a slightly more detailed idea of where we are by following our process in the [Solid test-suite repo](https://github.com/solid/test-suite).

As our current focus is on the code, my estimate is that our documentation will remain out-of-date for another month or two.

**Comment by Potherca** [comment] 2021-11-26 10:34
Fixed in 03c8e961772c324b4718e0e778a2a38054b3ef6d

**Closed as completed by Potherca** 2021-11-26 10:34 UTC
Labels: documentation
